[features]
seeds = false
skip-lint = false
[programs.devnet]
bridge_name_service = "BQqpUU12TqvMm6NRwM9Lv7vKZLWwWzgaZh2Q2qvkmcbi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/k/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
